# Healthy levels for young adults (age 20-39 years) - Reference ranges are approximate and may vary.

healthy_levels_young_adults = {
    "Albumin (g/dL)": {"min": 3.4, "max": 5.4},
    "Albumin (g/L)": {"min": 34, "max": 54},
    "Alanine aminotransferase ALT (U/L)": {"min": 5, "max": 40},
    "Aspartate aminotransferase AST (U/L)": {"min": 8, "max": 48},
    "Alkaline phosphatase (U/L)": {"min": 20, "max": 140},
    "Blood urea nitrogen (mg/dL)": {"min": 8, "max": 25},
    "Blood urea nitrogen (mmol/L)": {"min": 2.9, "max": 8.9},
    "Total calcium (mg/dL)": {"min": 8.6, "max": 10.4},
    "Total calcium (mmol/L)": {"min": 2.1, "max": 2.6},
    "Creatine Phosphokinase (CPK) (IU/L)": {"min": 38, "max": 308},
    "Cholesterol (mg/dL)": {"min": 125, "max": 200},
    "Cholesterol (mmol/L)": {"min": 3.24, "max": 5.18},
    "Bicarbonate (mmol/L)": {"min": 21, "max": 31},
    "Creatinine (mg/dL)": {"min": 0.7, "max": 1.3},
    "Creatinine (umol/L)": {"min": 61.9, "max": 115},
    "Gamma glutamyl transferase (U/L)": {"min": 5, "max": 85},
    "Glucose, serum (mg/dL)": {"min": 70, "max": 100},
    "Glucose, serum (mmol/L)": {"min": 3.9, "max": 5.6},
    "Iron, refrigerated (ug/dL)": {"min": 35, "max": 169},
    "Iron, refrigerated (umol/L)": {"min": 6.26, "max": 30.29},
    "Potassium (mmol/L)": {"min": 3.5, "max": 5.0},
    "Phosphorus (mg/dL)": {"min": 2.5, "max": 4.9},
    "Phosphorus (mmol/L)": {"min": 0.81, "max": 1.58},
    "Total bilirubin (mg/dL)": {"min": 0.2, "max": 1.2},
    "Total bilirubin (umol/L)": {"min": 3.42, "max": 20.51},
    "Total protein (g/dL)": {"min": 6.6, "max": 8.3},
    "Total protein (g/L)": {"min": 66, "max": 83},
    "Uric acid (mg/dL)": {"min": 2.4, "max": 7.2},
    "Uric acid (umol/L)": {"min": 142, "max": 428},
    "Sodium (mmol/L)": {"min": 135, "max": 146},
    "Lactate Dehydrogenase (U/L)": {"min": 85, "max": 270},
    "Chloride (mmol/L)": {"min": 96, "max": 106},
    "Osmolality (mmol/Kg)": {"min": 275, "max": 295},
    "Globulin (g/dL)": {"min": 2.3, "max": 3.5},
    "Globulin (g/L)": {"min": 26, "max": 35},
    "Triglycerides (mg/dL)": {"min": 30, "max": 150},
    "Triglycerides (mmol/L)": {"min": 0.34, "max": 1.69}
}



# Healthy levels for older adults (age 40-65 years)
older_adults_reference_ranges = {
    "Albumin (g/dL)": {"min": 3.4, "max": 5.4},
    "Albumin (g/L)": {"min": 34, "max": 54},
    "Alanine aminotransferase ALT (U/L)": {"min": 7, "max": 56},
    "Aspartate aminotransferase AST (U/L)": {"min": 10, "max": 40},
    "Alkaline phosphatase (U/L)": {"min": 25, "max": 150},
    "Blood urea nitrogen (mg/dL)": {"min": 8, "max": 25},
    "Blood urea nitrogen (mmol/L)": {"min": 2.9, "max": 8.9},
    "Total calcium (mg/dL)": {"min": 8.5, "max": 10.1},
    "Total calcium (mmol/L)": {"min": 2.1, "max": 2.5},
    "Creatine Phosphokinase (CPK) (IU/L)": {"min": 22, "max": 198},
    "Cholesterol (mg/dL)": {"min": 125, "max": 200},
    "Cholesterol (mmol/L)": {"min": 3.2, "max": 5.2},
    "Bicarbonate (mmol/L)": {"min": 23, "max": 32},
    "Creatinine (mg/dL)": {"min": 0.6, "max": 1.3},
    "Creatinine (umol/L)": {"min": 53, "max": 115},
    "Gamma glutamyl transferase (U/L)": {"min": 9, "max": 48},
    "Glucose, serum (mg/dL)": {"min": 70, "max": 100},
    "Glucose, serum (mmol/L)": {"min": 3.9, "max": 5.6},
    "Iron, refrigerated (ug/dL)": {"min": 50, "max": 170},
    "Iron, refrigerated (umol/L)": {"min": 8.9, "max": 30.4},
    "Lactate Dehydrogenase (U/L)": {"min": 85, "max": 195},
    "Phosphorus (mg/dL)": {"min": 2.5, "max": 4.5},
    "Phosphorus (mmol/L)": {"min": 0.81, "max": 1.45},
    "Total bilirubin (mg/dL)": {"min": 0.2, "max": 1.2},
    "Total bilirubin (umol/L)": {"min": 3.42, "max": 20.5},
    "Total protein (g/dL)": {"min": 6.4, "max": 8.3},
    "Total protein (g/L)": {"min": 64, "max": 83},
    "Uric acid (mg/dL)": {"min": 2.6, "max": 6.0},
    "Uric acid (umol/L)": {"min": 154, "max": 357},
    "Sodium (mmol/L)": {"min": 135, "max": 145},
    "Potassium (mmol/L)": {"min": 3.5, "max": 5.3},
    "Chloride (mmol/L)": {"min": 95, "max": 110},
    "Osmolality (mmol/Kg)": {"min": 275, "max": 295},
    "Globulin (g/dL)": {"min": 2.6, "max": 3.5},
    "Globulin (g/L)": {"min": 26, "max": 35},
    "Triglycerides (mg/dL)": {"min": 35, "max": 160},
    "Triglycerides (mmol/L)": {"min": 0.39, "max": 1.81}
}

# Healthy levels for elderly adults (65 years plus)
older_elderly_reference_ranges = {
    "Albumin (g/dL)": {"min": 3.4, "max": 5.4},
    "Albumin (g/L)": {"min": 34, "max": 54},
    "Alanine aminotransferase ALT (U/L)": {"min": 7, "max": 56},
    "Aspartate aminotransferase AST (U/L)": {"min": 10, "max": 40},
    "Alkaline phosphatase (U/L)": {"min": 25, "max": 150},
    "Blood urea nitrogen (mg/dL)": {"min": 8, "max": 25},
    "Blood urea nitrogen (mmol/L)": {"min": 2.9, "max": 8.9},
    "Total calcium (mg/dL)": {"min": 8.5, "max": 10.1},
    "Total calcium (mmol/L)": {"min": 2.1, "max": 2.5},
    "Creatine Phosphokinase (CPK) (IU/L)": {"min": 22, "max": 198},
    "Cholesterol (mg/dL)": {"min": 125, "max": 200},
    "Cholesterol (mmol/L)": {"min": 3.2, "max": 5.2},
    "Bicarbonate (mmol/L)": {"min": 23, "max": 32},
    "Creatinine (mg/dL)": {"min": 0.6, "max": 1.3},
    "Creatinine (umol/L)": {"min": 53, "max": 115},
    "Gamma glutamyl transferase (U/L)": {"min": 9, "max": 48},
    "Glucose, serum (mg/dL)": {"min": 70, "max": 100},
    "Glucose, serum (mmol/L)": {"min": 3.9, "max": 5.6},
    "Iron, refrigerated (ug/dL)": {"min": 50, "max": 170},
    "Iron, refrigerated (umol/L)": {"min": 8.9, "max": 30.4},
    "Lactate Dehydrogenase (U/L)": {"min": 85, "max": 195},
    "Phosphorus (mg/dL)": {"min": 2.5, "max": 4.5},
    "Phosphorus (mmol/L)": {"min": 0.81, "max": 1.45},
    "Total bilirubin (mg/dL)": {"min": 0.2, "max": 1.2},
    "Total bilirubin (umol/L)": {"min": 3.42, "max": 20.5},
    "Total protein (g/dL)": {"min": 6.4, "max": 8.3},
    "Total protein (g/L)": {"min": 64, "max": 83},
    "Uric acid (mg/dL)": {"min": 2.6, "max": 6.0},
    "Uric acid (umol/L)": {"min": 154, "max": 357},
    "Sodium (mmol/L)": {"min": 135, "max": 145},
    "Potassium (mmol/L)": {"min": 3.5, "max": 5.3},
    "Chloride (mmol/L)": {"min": 95, "max": 110},
    "Osmolality (mmol/Kg)": {"min": 275, "max": 295},
    "Globulin (g/dL)": {"min": 2.6, "max": 3.5},
    "Globulin (g/L)": {"min": 26, "max": 35},
    "Triglycerides (mg/dL)": {"min": 35, "max": 160},
    "Triglycerides (mmol/L)": {"min": 0.39, "max": 1.81}
}

            
       